// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabaseClient.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};
var textResult = (value) => ({
  content: [{ type: "text", text: JSON.stringify(value, null, 2) }]
});
var errorResult = (message) => ({
  content: [{ type: "text", text: message }],
  isError: true
});

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my crew profile",
  description: "Return the signed-in seafarer's SeaMinds crew profile: name, rank, nationality, vessel, availability and crew ID.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("crew_profiles").select(
      "id, first_name, last_name, rank, role, nationality, home_country, ship_name, vessel_type, years_at_sea, crew_unique_id, is_available, available_from, job_alerts_enabled, onboarding_complete"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("No crew profile found for this account yet.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/search-jobs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var search_jobs_default = defineTool2({
  name: "search_jobs",
  title: "Search maritime jobs",
  description: "Search current maritime job vacancies on SeaMinds by rank, vessel type or free-text keyword.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text keyword matched against job title and description."),
    rank: z.string().trim().optional().describe("Rank required, e.g. '2nd Officer', 'ETO Cadet'."),
    vessel_type: z.string().trim().optional().describe("Vessel type, e.g. 'Tanker', 'Bulk Carrier'."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of vacancies to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, rank, vessel_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    let q = supabaseForUser(ctx).from("external_vacancies").select(
      "id, title, rank_required, vessel_type, company_name, salary_text, salary_min, salary_max, joining_port, joining_date, contract_duration, apply_url, contact_email, contact_whatsapp, quality_score, fetched_at"
    ).eq("is_scam_flagged", false).gt("expires_at", (/* @__PURE__ */ new Date()).toISOString()).order("fetched_at", { ascending: false }).limit(limit ?? 10);
    if (rank) q = q.ilike("rank_required", `%${rank}%`);
    if (vessel_type) q = q.ilike("vessel_type", `%${vessel_type}%`);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, vacancies: data ?? [] });
  }
});

// src/lib/mcp/tools/get-my-smc-score.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_my_smc_score_default = defineTool3({
  name: "get_my_smc_score",
  title: "Get my SMC score",
  description: "Return the signed-in seafarer's latest Seafarer Merit Score (SMC) assessment result and dimension scores.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: pErr } = await supabase.from("crew_profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (pErr) return errorResult(pErr.message);
    if (!profile) return errorResult("No crew profile found for this account yet.");
    const { data, error } = await supabase.from("smc_assessments").select(
      "id, status, overall_score, score_band, technical_score, english_score, experience_score, behavioural_score, wellness_score, dimension_scores, certificate_id, recommendation, completed_at"
    ).eq("crew_profile_id", profile.id).order("completed_at", { ascending: false, nullsFirst: false }).limit(1).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("No SMC assessment found yet.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/update-availability.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var update_availability_default = defineTool4({
  name: "update_availability",
  title: "Update my availability",
  description: "Update the signed-in seafarer's availability for work, available-from date and job alert preference.",
  inputSchema: {
    is_available: z2.boolean().optional().describe("Whether the seafarer is currently available for work."),
    available_from: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date available from, YYYY-MM-DD."),
    job_alerts_enabled: z2.boolean().optional().describe("Whether to receive job alerts.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const patch = Object.fromEntries(Object.entries(input).filter(([, v]) => v !== void 0));
    if (Object.keys(patch).length === 0) return errorResult("Provide at least one field to update.");
    const { data, error } = await supabaseForUser(ctx).from("crew_profiles").update(patch).eq("user_id", ctx.getUserId()).select("is_available, available_from, job_alerts_enabled");
    if (error) return errorResult(error.message);
    if (!data?.length) return errorResult("No crew profile found to update.");
    return textResult(data[0]);
  }
});

// src/lib/mcp/index.ts
var projectRef = "luomzexqgcjtcmdlbevo";
var mcp_default = defineMcp({
  name: "seaminds-your-crew-companion",
  title: "SeaMinds: Your Crew Companion",
  version: "0.1.0",
  instructions: "Tools for SeaMinds, a companion app for seafarers. Use `get_my_profile` for the signed-in seafarer's crew profile, `get_my_smc_score` for their latest Seafarer Merit Score, `search_jobs` to find maritime vacancies, and `update_availability` to change their availability for work. Wellness chat and welfare data are private and never exposed.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_smc_score_default, search_jobs_default, update_availability_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
